/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SwaggerConfig.h"

#include <QNetworkRequest>

#ifdef QT_QML_LIB
#include <QQmlEngine>
#endif // QT_QML_LIB

namespace Swagger {

SwaggerConfig::SwaggerConfig(QObject *parent)
: QObject(parent)
{
}

SwaggerConfig::SwaggerConfig(const QUrl &url, QObject *parent)
: QObject(parent)
, m_url(url)
{
}

SwaggerConfig::~SwaggerConfig()
{
}

void SwaggerConfig::setUrl(const QUrl &url)
{
    m_url = url;
}

QUrl SwaggerConfig::url() const
{
    return m_url;
}

void SwaggerConfig::setApiKey(const QString& key, const QByteArray &value)
{
    m_apiKeys.insert(key, value);
}

void SwaggerConfig::removeApiKey(const QString &key)
{
    m_apiKeys.remove(key);
}

QByteArray SwaggerConfig::apiKey(const QString &key) const
{
    return m_apiKeys.value(key);
}

void SwaggerConfig::setNetworkAccessManager(QNetworkAccessManager *networkAccessManager)
{
    if (m_networkAccessManager == networkAccessManager) {
        return;
    }

    if (m_networkAccessManager && m_networkAccessManager->parent() == this) {
        m_networkAccessManager->deleteLater();
    }

    m_networkAccessManager = networkAccessManager;
}

QNetworkAccessManager *SwaggerConfig::networkAccessManager()
{
    if (!m_networkAccessManager) {
    #ifdef QT_QML_LIB
        QQmlEngine *engine = qmlEngine(this);
        if (engine) {
            m_networkAccessManager = engine->networkAccessManager();
        }
    #endif // QT_QML_LIB

        if (!m_networkAccessManager) {
            m_networkAccessManager = new QNetworkAccessManager(this);
        }
    }

    return m_networkAccessManager;
}

void SwaggerConfig::prepareRequest(QNetworkRequest *request)
{
    request->setRawHeader("User-Agent", "Swagger-Client");
}

void SwaggerConfig::processReply(QNetworkReply *reply)
{
    Q_UNUSED(reply);
}

} // namespace Swagger
