/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
* SWGApiResponse.h
*
* Describes the result of uploading an image resource
*/

#ifndef SWGApiResponse_PRIVATE_H_
#define SWGApiResponse_PRIVATE_H_


#include <QString>
#include <QSharedData>


namespace Swagger {

class SWGApiResponseData : public QSharedData {
public:
    SWGApiResponseData()
    : QSharedData(), code(0)
    {
    }

    SWGApiResponseData(const SWGApiResponseData &other)
    : QSharedData(other)
    , code(other.code)
    , type(other.type)
    , message(other.message)
    {
    }

    ~SWGApiResponseData() {
    }

    qint32 code;
    QString type;
    QString message;
};

} /* namespace Swagger */

#endif /* SWGApiResponse_PRIVATE_H_ */
