/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGApiResponse.h
 * 
 * Describes the result of uploading an image resource
 */

#ifndef SWGApiResponse_H_
#define SWGApiResponse_H_

#include "SwaggerConfig.h"

#include <QString>
#include <QSharedDataPointer>


namespace Swagger {

class SWGApiResponseData;

class SWGApiResponse {
public:
    SWGApiResponse();
    SWGApiResponse(const SWGApiResponse &other);
    ~SWGApiResponse();

    qint32 code() const;
    void setCode(const qint32 &code);

    QString type() const;
    void setType(const QString &type);

    QString message() const;
    void setMessage(const QString &message);

private:
    QSharedDataPointer<SWGApiResponseData> d;
};

}

Q_DECLARE_TYPEINFO(Swagger::SWGApiResponse, Q_MOVABLE_TYPE);

#endif /* SWGApiResponse_H_ */
