/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
* SWGCategory.h
*
* A category for a pet
*/

#ifndef SWGCategory_PRIVATE_H_
#define SWGCategory_PRIVATE_H_


#include <QString>
#include <QSharedData>


namespace Swagger {

class SWGCategoryData : public QSharedData {
public:
    SWGCategoryData()
    : QSharedData(), id(0L)
    {
    }

    SWGCategoryData(const SWGCategoryData &other)
    : QSharedData(other)
    , id(other.id)
    , name(other.name)
    {
    }

    ~SWGCategoryData() {
    }

    qint64 id;
    QString name;
};

} /* namespace Swagger */

#endif /* SWGCategory_PRIVATE_H_ */
