/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCategory.h"
#include "SWGCategory_p.h"

namespace Swagger {

SWGCategory::SWGCategory()
: d(new SWGCategoryData)
{
}

SWGCategory::SWGCategory(const SWGCategory &other)
: d(other.d)
{
}

SWGCategory::~SWGCategory()
{
}

SWGCategory &SWGCategory::operator =(const SWGCategory &other)
{
    d = other.d;
    return *this;
}

qint64 SWGCategory::id() const
{
    return d->id;
}

void SWGCategory::setId(const qint64 &id)
{
    d->id = id;
}

QString SWGCategory::name() const
{
    return d->name;
}

void SWGCategory::setName(const QString &name)
{
    d->name = name;
}


} /* namespace Swagger */

