/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGOrder.h"
#include "SWGOrder_p.h"

namespace Swagger {

SWGOrder::SWGOrder()
: d(new SWGOrderData)
{
}

SWGOrder::SWGOrder(const SWGOrder &other)
: d(other.d)
{
}

SWGOrder::~SWGOrder()
{
}

qint64 SWGOrder::id() const
{
    return d->id;
}

void SWGOrder::setId(const qint64 &id)
{
    d->id = id;
}

qint64 SWGOrder::petId() const
{
    return d->pet_id;
}

void SWGOrder::setPetId(const qint64 &pet_id)
{
    d->pet_id = pet_id;
}

qint32 SWGOrder::quantity() const
{
    return d->quantity;
}

void SWGOrder::setQuantity(const qint32 &quantity)
{
    d->quantity = quantity;
}

QDateTime SWGOrder::shipDate() const
{
    return d->ship_date;
}

void SWGOrder::setShipDate(const QDateTime &ship_date)
{
    d->ship_date = ship_date;
}

QString SWGOrder::status() const
{
    return d->status;
}

void SWGOrder::setStatus(const QString &status)
{
    d->status = status;
}

bool SWGOrder::complete() const
{
    return d->complete;
}

void SWGOrder::setComplete(const bool &complete)
{
    d->complete = complete;
}


} /* namespace Swagger */

