/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
* SWGOrder.h
*
* An order for a pets from the pet store
*/

#ifndef SWGOrder_PRIVATE_H_
#define SWGOrder_PRIVATE_H_


#include <QDateTime>
#include <QString>
#include <QSharedData>


namespace Swagger {

class SWGOrderData : public QSharedData {
public:
    SWGOrderData()
    : QSharedData(), id(0L), pet_id(0L), quantity(0), complete(false)
    {
    }

    SWGOrderData(const SWGOrderData &other)
    : QSharedData(other)
    , id(other.id)
    , pet_id(other.pet_id)
    , quantity(other.quantity)
    , ship_date(other.ship_date)
    , status(other.status)
    , complete(other.complete)
    {
    }

    ~SWGOrderData() {
    }

    qint64 id;
    qint64 pet_id;
    qint32 quantity;
    QDateTime ship_date;
    QString status;
    bool complete;
};

} /* namespace Swagger */

#endif /* SWGOrder_PRIVATE_H_ */
