/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGOrder.h"
#include "SWGOrder_p.h"

namespace Swagger {

SWGOrder::SWGOrder()
: d(new SWGOrderData)
{
}

SWGOrder::SWGOrder(const SWGOrder &other)
: d(other.d)
{
}

SWGOrder::~SWGOrder()
{
}

SWGOrder &SWGOrder::operator =(const SWGOrder &other)
{
    d = other.d;
    return *this;
}

bool SWGOrder::operator ==(const SWGOrder &cmp) const
{
    if (d == cmp.d) {
        return true;
    }

    return (
        d->id == cmp.d->id &&
        d->petId == cmp.d->petId &&
        d->quantity == cmp.d->quantity &&
        d->shipDate == cmp.d->shipDate &&
        d->status == cmp.d->status &&
        d->complete == cmp.d->complete
    );
}

qint64 SWGOrder::id() const
{
    return d->id;
}

void SWGOrder::setId(const qint64 &id)
{
    d->id = id;
}

qint64 SWGOrder::petId() const
{
    return d->petId;
}

void SWGOrder::setPetId(const qint64 &petId)
{
    d->petId = petId;
}

qint32 SWGOrder::quantity() const
{
    return d->quantity;
}

void SWGOrder::setQuantity(const qint32 &quantity)
{
    d->quantity = quantity;
}

QDateTime SWGOrder::shipDate() const
{
    return d->shipDate;
}

void SWGOrder::setShipDate(const QDateTime &shipDate)
{
    d->shipDate = shipDate;
}

QString SWGOrder::status() const
{
    return d->status;
}

void SWGOrder::setStatus(const QString &status)
{
    d->status = status;
}

bool SWGOrder::complete() const
{
    return d->complete;
}

void SWGOrder::setComplete(const bool &complete)
{
    d->complete = complete;
}

QDebug operator <<(QDebug stream, const SWGOrder &obj)
{
    QDebugStateSaver saver(stream);
    stream.nospace()
        << "id: " << obj.id() << ", "
        << "petId: " << obj.petId() << ", "
        << "quantity: " << obj.quantity() << ", "
        << "shipDate: " << obj.shipDate() << ", "
        << "status: " << obj.status() << ", "
        << "complete: " << obj.complete();

    return stream;
}

} // namespace Swagger

