/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
* SWGPet.h
*
* A pet for sale in the pet store
*/

#ifndef SWGPet_PRIVATE_H_
#define SWGPet_PRIVATE_H_


#include "SWGCategory.h"
#include "SWGTag.h"
#include <QList>
#include <QString>
#include <QSharedData>


namespace Swagger {

class SWGPetData : public QSharedData {
public:
    SWGPetData()
    : QSharedData(), id(0L)
    {
    }

    SWGPetData(const SWGPetData &other)
    : QSharedData(other)
    , id(other.id)
    , category(other.category)
    , name(other.name)
    , photoUrls(other.photoUrls)
    , tags(other.tags)
    , status(other.status)
    {
    }

    ~SWGPetData() {
    }

    qint64 id;
    SWGCategory category;
    QString name;
    QList<QString> photoUrls;
    QList<SWGTag> tags;
    QString status;
};

} // namespace Swagger

#endif /* SWGPet_PRIVATE_H_ */
