/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGTag.h
 * 
 * A tag for a pet
 */

#ifndef SWGTag_H_
#define SWGTag_H_

#include "SwaggerConfig.h"

#include <QString>
#include <QDebug>
#include <QSharedDataPointer>


namespace Swagger {

class SWGTagData;

class SWGTag {
    Q_GADGET
    Q_PROPERTY(qint64 id READ id)
    Q_PROPERTY(QString name READ name)
public:
    SWGTag();
    SWGTag(const SWGTag &other);
    ~SWGTag();

    SWGTag &operator =(const SWGTag &other);

    bool operator ==(const SWGTag &cmp) const;

    qint64 id() const;
    void setId(const qint64 &id);

    QString name() const;
    void setName(const QString &name);

private:
    QSharedDataPointer<SWGTagData> d;
};

QDebug operator <<(QDebug stream, const SWGTag &obj);

} // namespace Swagger

Q_DECLARE_TYPEINFO(Swagger::SWGTag, Q_MOVABLE_TYPE);
Q_DECLARE_METATYPE(Swagger::SWGTag)

#endif /* SWGTag_H_ */
