/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGUser.h
 * 
 * A User who is purchasing from the pet store
 */

#ifndef SWGUser_H_
#define SWGUser_H_

#include "SwaggerConfig.h"

#include <QString>
#include <QDebug>
#include <QSharedDataPointer>


namespace Swagger {

class SWGUserData;

class SWGUser {
    Q_GADGET
    Q_PROPERTY(qint64 id READ id)
    Q_PROPERTY(QString username READ username)
    Q_PROPERTY(QString firstName READ firstName)
    Q_PROPERTY(QString lastName READ lastName)
    Q_PROPERTY(QString email READ email)
    Q_PROPERTY(QString password READ password)
    Q_PROPERTY(QString phone READ phone)
    Q_PROPERTY(qint32 userStatus READ userStatus)
public:
    SWGUser();
    SWGUser(const SWGUser &other);
    ~SWGUser();

    SWGUser &operator =(const SWGUser &other);

    bool operator ==(const SWGUser &cmp) const;

    qint64 id() const;
    void setId(const qint64 &id);

    QString username() const;
    void setUsername(const QString &username);

    QString firstName() const;
    void setFirstName(const QString &firstName);

    QString lastName() const;
    void setLastName(const QString &lastName);

    QString email() const;
    void setEmail(const QString &email);

    QString password() const;
    void setPassword(const QString &password);

    QString phone() const;
    void setPhone(const QString &phone);

    qint32 userStatus() const;
    void setUserStatus(const qint32 &userStatus);

private:
    QSharedDataPointer<SWGUserData> d;
};

QDebug operator <<(QDebug stream, const SWGUser &obj);

} // namespace Swagger

Q_DECLARE_TYPEINFO(Swagger::SWGUser, Q_MOVABLE_TYPE);
Q_DECLARE_METATYPE(Swagger::SWGUser)

#endif /* SWGUser_H_ */
