/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
* SWGUser.h
*
* A User who is purchasing from the pet store
*/

#ifndef SWGUser_PRIVATE_H_
#define SWGUser_PRIVATE_H_


#include <QString>
#include <QSharedData>


namespace Swagger {

class SWGUserData : public QSharedData {
public:
    SWGUserData()
    : QSharedData(), id(0L), user_status(0)
    {
    }

    SWGUserData(const SWGUserData &other)
    : QSharedData(other)
    , id(other.id)
    , username(other.username)
    , first_name(other.first_name)
    , last_name(other.last_name)
    , email(other.email)
    , password(other.password)
    , phone(other.phone)
    , user_status(other.user_status)
    {
    }

    ~SWGUserData() {
    }

    qint64 id;
    QString username;
    QString first_name;
    QString last_name;
    QString email;
    QString password;
    QString phone;
    qint32 user_status;
};

} /* namespace Swagger */

#endif /* SWGUser_PRIVATE_H_ */
